# Generated by Django 3.2.18 on 2023-06-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(to='blog.BlogCategory'),
        ),
    ]
