# Generated by Django 3.2.18 on 2023-04-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('short_des', models.CharField(max_length=100)),
                ('lang_des', models.TextField()),
                ('product_Property', models.CharField(max_length=200)),
                ('orginal_price', models.IntegerField()),
                ('Discounted_price', models.IntegerField(blank=True, null=True)),
                ('discount_percent', models.CharField(blank=True, max_length=2, null=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
