# Generated by Django 3.2.18 on 2023-04-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20230408_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='image1',
            field=models.ImageField(upload_to='product'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='image2',
            field=models.ImageField(upload_to='product'),
        ),
    ]
