# Generated by Django 3.2.18 on 2023-04-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230408_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='create_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
