# Generated by Django 3.2.18 on 2023-04-15 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20230413_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='mainparent',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='parent',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productcategory'),
        ),
        migrations.AddField(
            model_name='productlist',
            name='category',
            field=models.ManyToManyField(to='shop.ProductCategory'),
        ),
        migrations.DeleteModel(
            name='MainCtegory',
        ),
    ]
