# Generated by Django 3.2.18 on 2023-05-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_baner_url_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baner',
            name='url_img',
            field=models.URLField(max_length=100),
        ),
    ]
