# Generated by Django 3.2.18 on 2023-05-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='img1',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='img2',
        ),
    ]
