# Generated by Django 3.2.18 on 2023-04-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('des', models.TextField()),
                ('img', models.ImageField(upload_to='about')),
                ('subtitle1', models.CharField(max_length=50)),
                ('subtitle2', models.CharField(max_length=50)),
                ('subtitle3', models.CharField(max_length=50)),
                ('sub_des1', models.TextField()),
                ('sub_des2', models.TextField()),
                ('sub_des3', models.TextField()),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
