# Generated by Django 3.2.18 on 2023-05-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_myuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='addres',
            field=models.TextField(blank=True, null=True),
        ),
    ]
