# Generated by Django 3.2.18 on 2023-04-16 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0003_alter_sitesetting_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterTital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان اصلی فوتر')),
            ],
            options={
                'verbose_name': 'عنوان اصلی فوتر',
                'verbose_name_plural': 'عناوین اصلی فوتر',
            },
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='number1',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='number2',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='لینک فوتر')),
                ('url_tital', models.URLField(max_length=100, verbose_name='url لینک')),
                ('footer_link_tital', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='site_setting.footertital', verbose_name='لینک فوتر')),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': 'لینکهای فوتر',
            },
        ),
    ]
