# Generated by Django 3.2.18 on 2023-04-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0004_auto_20230416_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='addres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='locaton',
            field=models.TextField(blank=True, null=True),
        ),
    ]
