# Generated by Django 3.2.18 on 2023-04-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0005_auto_20230417_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='addres',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
