# Generated by Django 3.2.18 on 2023-04-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0006_auto_20230417_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('subtitle', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='slider')),
                ('butten_url', models.URLField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلاید ها',
            },
        ),
    ]
